name: CI CD Pipeline # This is the name you will see in the UI

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Running ci_cd.yml workflow"
